# serverless.yml

service: ${file(package.json):name, 'studio-sauce-api-v1'}

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

# plugins:
# - serverless-webpack

custom:
  stage: ${opt:stage, self:provider.stage}
  defaultStage: development
  defaultRegion: us-east-1
  serverless-offline:
    noPrependStageInUrl: true
    host: 0.0.0.0
    port: 3000
  dotenv:
    include:
      - MONGODB_URL
      - PROJECT_NAME
      - PROJECT_VERSION
      - AWS_ACCOUNT_ID
      - NODE_ENV

# custom:
#   webpack:
#     webpackConfig: webpack.config.js
#     includeModules: true
#     packager: yarn

provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}
  runtime: nodejs12.x
  memorySize: 1024
  timeout: 30

functions:
  api:
    handler: src/app.handler
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/studio-sauce-api-${env:NODE_ENV}-identity-lambda
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /auth/{proxy+}
          method: ANY
          cors: true
          # authorizer:
          # arn: arn:aws:cognito-idp:${self:provider.region}:${env:AWS_ACCOUNT_ID}:userpool/${env:USERPOOL_ID}
      - http:
          path: /public/{proxy+}
          method: ANY
          cors: true
