# serverless.yml

service: studio-sauce-api

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  defaultStage: dev
  defaultRegion: us-east-1
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: yarn
  serverless-offline:
    noPrependStageInUrl: true
    host: 0.0.0.0
    port: 3000
  dotenv:
    include:
      - MONGODB_URL
      - PROJECT_NAME
      - PROJECT_VERSION
      - AWS_ACCOUNT_ID
      - NODE_ENV
      - PORT
      - JWT_SECRET
      - JWT_ACCESS_EXPIRATION_MINUTES
      - JWT_REFRESH_EXPIRATION_DAYS

provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}
  runtime: nodejs12.x
  memorySize: 1024
  timeout: 300

functions:
  api:
    handler: src/app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
